####################################################################################################
# config
####################################################################################################

goapp := 'Mimir'
goexe := 'mimir'

####################################################################################################
